export type Employer = {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  jobTitle: string;
  department: string;
  manager: string;
  location: string;
  company: string;
  hireDate: string;
  salary: number;
  bonus: number;
  performanceRating: string;
  lastPromotion: string;
  nextReview: string;
  employmentStatus: string;
  dateOfBirth: string;
  address: string;
  phoneNumber: string;
  emergencyContact: string;
  startDate: string;
  endDate: string;
  jobDescription: string;
  skills: string;
  education: string;
  certifications: string;
  languages: string;
  nationality: string;
  ethnicity: string;
  disabilityStatus: string;
  veteranStatus: string;
};

export type Patient = {
  id: number;
  firstName: string;
  lastName: string;
  age: number;
  gender: string;
  diagnosis: string;
  medication: string;
  dosage: string;
  frequency: string;
  physician: string;
  lastVisit: string;
  nextVisit: string;
  insuranceProvider: string;
  policyNumber: string;
  medicalHistory: string;
  emergencyContact: string;
  allergies: string;
  bloodType: string;
  height: string;
  weight: string;
  bmi: string;
  smokingStatus: string;
  alcoholUse: string;
  exerciseFrequency: string;
  diet: string;
  familyHistory: string;
  immunizationStatus: string;
  lastCheckup: string;
};

export type TimelineRecord = {
  id: string;
  dob: string;
  gender: string;
  allowed: string;
  benefit: string;
  billing_class: string;
  charges: string;
  code: string;
  copay: string;
  dos_from: string | Date;
  dx1: string;
  dx2: string;
  line: string;
  patient_id: string;
  rend_provider_id: string;
  revcode: string;
  units: string;
};

export interface TimelineCardProps {
  date: string;
  totalAllowed: number;
  codes: string[];
  diagnostics: string[];
}
